// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function ExportToFile() {
  return window['go']['main']['App']['ExportToFile']();
}

export function GetDiagnosticsStatus() {
  return window['go']['main']['App']['GetDiagnosticsStatus']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetLibreSpeedServers() {
  return window['go']['main']['App']['GetLibreSpeedServers']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSpeedtestHistory() {
  return window['go']['main']['App']['GetSpeedtestHistory']();
}

export function SetMaximizeButtonRect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetMaximizeButtonRect'](arg1, arg2, arg3, arg4);
}

export function StartDiagnostics(arg1) {
  return window['go']['main']['App']['StartDiagnostics'](arg1);
}

export function StartLibreSpeedTest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartLibreSpeedTest'](arg1, arg2, arg3, arg4, arg5);
}

export function StartSpeedtest(arg1) {
  return window['go']['main']['App']['StartSpeedtest'](arg1);
}

export function StopDiagnostics() {
  return window['go']['main']['App']['StopDiagnostics']();
}

export function StopSpeedtest() {
  return window['go']['main']['App']['StopSpeedtest']();
}
