// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteHost(arg1:string):Promise<void>;

export function ExportToFile():Promise<void>;

export function GetDiagnosticsStatus():Promise<boolean>;

export function GetHistory():Promise<Array<string>>;

export function GetLibreSpeedServers():Promise<Array<main.LibreSpeedServer>>;

export function GetNetworkInfo():Promise<main.NetworkInfo>;

export function GetServers():Promise<Array<main.SpeedServer>>;

export function GetSessions():Promise<Array<main.DiagSession>>;

export function GetSpeedtestHistory():Promise<Array<main.SpeedtestSession>>;

export function SetMaximizeButtonRect(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function StartDiagnostics(arg1:string):Promise<void>;

export function StartLibreSpeedTest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function StartSpeedtest(arg1:string):Promise<void>;

export function StopDiagnostics():Promise<void>;

export function StopSpeedtest():Promise<void>;
